"""
Django settings for the basic_project example.

Generated by 'django-admin startproject' using Django 6.1 and adapted
to demonstrate django-binary-builder.
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: the packaged application reads this value from the
# runtime environment snapshot built from .env at build time.
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-lczgcs7*b8y5-g29a3ee^2y7deglsr!4o)d_#@@8%d(po&3c9g",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "0") == "1"

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get(
        "DJANGO_ALLOWED_HOSTS",
        "127.0.0.1,localhost",
    ).split(",")
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_binary_builder",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "basic_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "basic_project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
# The packaged application overrides this at runtime to use a SQLite
# database inside the persistent runtime data directory.

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "static/"

STATIC_ROOT = BASE_DIR / "staticfiles"


# django-binary-builder configuration
# https://github.com/swarfte/django-binary-builder

DJANGO_BINARY_BUILDER = {
    "NAME": "Basic Project",
    "VERSION": "0.1.0",
    "PUBLISHER": "Example Company",
    "EXECUTABLE_NAME": "basic-project",
    "OUTPUT_DIR": BASE_DIR / "release",
    "WORK_DIR": BASE_DIR / ".django-binary-builder",
    "SERVER": {
        "HOST": "127.0.0.1",
        "PORT": 8765,
        "THREADS": 8,
        "OPEN_BROWSER": True,
    },
    "ENVIRONMENT": {
        "ENABLED": True,
        "FILES": [BASE_DIR / ".env"],
        "INCLUDE": [
            "DJANGO_SECRET_KEY",
            "DJANGO_ALLOWED_HOSTS",
            "APP_FEATURE_*",
        ],
        "EXCLUDE": [
            "DJANGO_BINARY_ADMIN_PASSWORD",
            "DJANGO_BINARY_DB_PASSWORD",
        ],
        "REQUIRED": [],
        # DJANGO_SECRET_KEY matches the secret-name policy; including
        # it in the snapshot requires explicitly accepting the risk.
        "ALLOW_SECRETS": True,
    },
    "DATABASE": {
        "MODE": "sqlite",
        "RUN_MIGRATIONS": True,
        "SQLITE": {
            "FILENAME": "db.sqlite3",
        },
    },
    "INITIAL_ADMIN": {
        "ENABLED": True,
        "SQLITE_ONLY": True,
        "REQUIRE_PASSWORD_CHANGE": True,
    },
    "RUNTIME": {
        "COMPANY_DIRECTORY": "ExampleCompany",
        "APPLICATION_DIRECTORY": "BasicProject",
    },
    "BUILD": {
        "MODE": "onedir",
        "CONSOLE": True,
    },
}
